server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      # You should add here the filters, routes, load balancing, etc
eureka:
  client:
    register-with-eureka: false